# Generated by Django 4.0.3 on 2022-04-29 06:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_alter_district_options_alter_state_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(error_messages={'invalid': 'Enter a valid 10 digit mobile numberwithout spaces, + or isd code.', 'required': 'Mobile number is required'}, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^[6-9]\\d{9}$')], verbose_name='Mobile Number')),
                ('type', models.CharField(choices=[('SUPER_USER', 'SUPER_USER'), ('ADMIN', 'ADMIN'), ('TSP', 'TSP'), ('USER', 'USER')], default='USER', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.district')),
                ('tsp_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tsp_companies', to='common.tsp')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
