# Generated by Django 4.0.3 on 2022-04-18 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(error_messages={'invalid': 'Enter a valid 10 digit mobile numberwithout spaces, + or isd code.', 'required': 'Mobile number is required'}, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^[6-9]\\d{9}$')], verbose_name='Mobile Number')),
                ('district', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('ADMIN', 'ADMIN'), ('TSP', 'TSP'), ('USER', 'USER')], default='USER', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
