# Generated by Django 4.0.3 on 2022-04-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('SUPER_USER', 'SUPER_USER'), ('ADMIN', 'ADMIN'), ('TSP', 'TSP'), ('USER', 'USER')], default='USER', max_length=255),
        ),
    ]
