# Generated by Django 4.0.3 on 2022-05-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
