# Generated by Django 4.0.3 on 2022-05-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='st',
            field=models.CharField(default='ASSAM', max_length=200),
        ),
    ]
