# Generated by Django 4.0.3 on 2022-04-29 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_state_district'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['id']},
        ),
    ]
