# Generated by Django 4.0.3 on 2022-05-04 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_district_options_alter_state_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tsp',
            options={'ordering': ['id']},
        ),
    ]
