# Generated by Django 4.0.3 on 2022-05-24 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_district_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='state',
        ),
    ]
