# Generated by Django 4.0.3 on 2022-04-18 12:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Invalid ip address', regex='\\b((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\\.|$)){4}\\b')])),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tsp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsp', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserRequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_date', models.DateField()),
                ('sys_time', models.TimeField()),
                ('target_type', models.CharField(choices=[('MOBILE_NUMBER', 'MOBILE_NUMBER'), ('IMEI_NUMBER', 'IMEI_NUMBER'), ('CELL_ID', 'CELL_ID'), ('IP_ADDRESS', 'IP_ADDRESS')], max_length=200)),
                ('case_ref', models.CharField(max_length=200)),
                ('case_type', models.CharField(max_length=200)),
                ('request_to_provide', models.CharField(choices=[('CDR', 'CDR'), ('IPDR', 'IPDR'), ('TOWER_DUMP', 'TOWER_DUMP'), ('SDR', 'SDR')], max_length=200)),
                ('mobile_number', models.BigIntegerField(validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^[6-9]\\d{9}$')])),
                ('cell_id', models.CharField(max_length=200)),
                ('imei', models.CharField(max_length=200)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('time_from', models.TimeField(blank=True, null=True)),
                ('time_to', models.TimeField(blank=True, null=True)),
                ('duration_date_from', models.DateField()),
                ('duration_date_to', models.DateField()),
                ('duration_time_from', models.TimeField()),
                ('duration_time_to', models.TimeField()),
                ('file', models.FileField(blank=True, upload_to='doc')),
                ('form_status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('REJECT', 'REJECT')], default='pending', max_length=200, null=True)),
                ('reject_msg', models.CharField(blank=True, default='rejected', max_length=200)),
                ('requested_date', models.DateField(blank=True)),
                ('replied_date', models.DateField(blank=True)),
                ('ip_port', models.ManyToManyField(to='user_request_form.ipport')),
                ('select_tsp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_request_form.tsp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
