# Generated by Django 4.0.3 on 2022-04-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequestform',
            name='form_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('REJECT', 'REJECT')], default='PENDING', max_length=200, null=True),
        ),
    ]
