# Generated by Django 4.0.3 on 2022-04-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request_form', '0002_alter_userrequestform_form_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequestform',
            name='approval_or_reject_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrequestform',
            name='approval_or_reject_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrequestform',
            name='reject_msg_cyberdrome',
            field=models.CharField(blank=True, default='Due to incomplete information', max_length=200),
        ),
    ]
