# Generated by Django 4.0.3 on 2022-05-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request_form', '0002_rejectiontable_reject_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequestform',
            name='admin_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('REJECT', 'REJECT')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userrequestform',
            name='tsp_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('REJECT', 'REJECT')], default='PENDING', max_length=200, null=True),
        ),
    ]
