# Generated by Django 4.0.3 on 2022-05-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request_form', '0003_userrequestform_admin_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequestform',
            name='admin_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('APPROVE', 'APPROVE'), ('REJECT', 'REJECT')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userrequestform',
            name='form_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('APPROVE', 'APPROVE'), ('REJECT', 'REJECT')], default='PENDING', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userrequestform',
            name='requested_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrequestform',
            name='tsp_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('APPROVE', 'APPROVE'), ('REJECT', 'REJECT')], default='PENDING', max_length=200, null=True),
        ),
    ]
