# Generated by Django 4.0.3 on 2022-04-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request_form', '0003_userrequestform_approval_or_reject_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequestform',
            name='tsp_file',
            field=models.FileField(blank=True, upload_to='tsp_doc'),
        ),
        migrations.AlterField(
            model_name='userrequestform',
            name='request_to_provide',
            field=models.CharField(choices=[('CDR', 'CDR'), ('IPDR', 'IPDR'), ('TOWER_DUMP', 'TOWER_DUMP'), ('SDR', 'SDR'), ('TDR', 'TDR')], max_length=200),
        ),
    ]
