# Generated by Django 4.0.3 on 2022-05-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request_form', '0004_alter_userrequestform_admin_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequestform',
            name='replied_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
