# Generated by Django 4.0.3 on 2022-05-09 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_request_form', '0005_alter_userrequestform_replied_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequestform',
            name='tsp_status',
        ),
    ]
