# Generated by Django 4.0.3 on 2022-05-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request_form', '0008_userrequestform_reject_msg_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequestform',
            name='ip_port',
            field=models.ManyToManyField(blank=True, null=True, to='user_request_form.ipport'),
        ),
    ]
