# Generated by Django 4.0.3 on 2022-05-16 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request_form', '0009_alter_userrequestform_ip_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipport',
            name='ip',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='Invalid ip address', regex='\\b((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\\.|$)){4}\\b')]),
        ),
        migrations.AlterField(
            model_name='ipport',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
