# Generated by Django 4.0.3 on 2022-05-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request_form', '0010_alter_ipport_ip_alter_ipport_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequestform',
            name='ip_port',
            field=models.ManyToManyField(blank=True, to='user_request_form.ipport'),
        ),
    ]
