# Generated by Django 4.0.3 on 2022-05-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request_form', '0011_alter_userrequestform_ip_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequestform',
            name='updated_date_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userrequestform',
            name='updated_time_at',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrequestform',
            name='sys_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrequestform',
            name='sys_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
