# Generated by Django 4.0.3 on 2022-05-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request_form', '0013_remove_userrequestform_updated_date_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequestform',
            name='updated_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
