# Generated by Django 4.0.3 on 2022-05-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request_form', '0014_userrequestform_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequestform',
            name='updated_by',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
