# Generated by Django 4.0.3 on 2022-05-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request_form', '0016_rename_updated_by_userrequestform_updated_by_tsp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequestform',
            name='sys_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrequestform',
            name='sys_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
