# Generated by Django 4.0.3 on 2022-05-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request_form', '0017_alter_userrequestform_sys_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequestform',
            name='updated_by_tsp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
